url: http://fishmanandwife.com
baseurl:

# Site settings
title: "#fishmanAndWife"
email: info@fishmanandwife.com
description: "Welcome to the wedding website of Rebecca Minerd and Adam Fishman!  Taking place in Cleveland, OH on October 7, 2017"


# Team names, titles and social links #TODO - put wedding party here?
people:
  - name: Ryan Irvine
    pic: 1
    position: Best Man
    bio: Ryan and Adam met at their first job after college in Cleveland, and have worked together now at four different jobs. On purpose, not by accident! 
  - name: Alex Janes
    pic: 2
    position: Groomsman
    bio: Alex is one of Adam's first friends from college and the two then lived together off-campus and both always did the dishes without complaining.
  - name: Dan Gregorich
    pic: 3
    position: Groomsman
    bio: Dan and Adam have been friends since high school and have travelled the world together, including trips to Spain and Japan!
  - name: Steve Kemeny
    pic: 4
    position: Groomsman
    bio: Steve was the first friend Adam made in college, when his parents and Steve's parents met in the dorm hallway as they were helping move them in at Virginia Tech.
  - name: Marshall Walcer
    pic: 5
    position: Groomsman
    bio: Marshall and Adam became friends as cub scouts. They achieved a glorious 15 minutes of fame together starring as an alien and robot in the Solon Library summer reading program promo video.

  - name: Michelle Doyle
    pic: 6
    position: Maid of Honor
    bio: Michelle and Rebecca’s friendship began while consoling one another over a bucket of Moose tracks ice cream, after we both did not make the eighth-grade cheerleading squad, what else was there to live for? These two have had each other’s tracks, I mean backs, ever sense.
  - name: Nicole DeChant
    pic: 7
    position: Bridesmaid
    bio: Nicole and Rebecca met in Junior high school. These two have shared many things together over the years, an apartment, the love of shoes and a few late nights. These ladies have made some great memories together.
  - name: Jacqueline Gedeon
    pic: 8
    position: Bridesmaid
    bio: What is there to say? Jacqueline is going to be a fabulous sister in law, she’s a great sailor and she puts up with Rebecca’s brother. One may say she is a triple threat.
  - name: Kathy Marino
    pic: 9
    position: Bridesmaid
    bio: Definitely, nothing but love, and laughs when these two get together. You can usually find Kathy and Rebecca hanging out by a nice fire, reminiscing about days gone by and singing along to almost any Broadway musical we can remember the words to.
  - name: Jillian Tubbs
    pic: 10
    position: Bridesmaid
    bio: Let’s just say our families get each other. Jillian and Rebecca bonded in High School, singing in Choir and playing Tennis. Fun times were always had whenever these two got together.
  - name: Morgan Dotlich
    pic: 11
    position: Junior Bridesmaid
    bio: More recently known as TINK! -Morgan and Rebecca are cousins and have always been close. Rebecca and Morgan share a love for the important things in life, good music, friends and family.

  - name: Lauren Becker & Lila Becker
    pic: 12
    position: Flower Girls
    bio: Lauren and Lila are Rebecca’s youngest cousins. Rounding off the Becker grandchildren at number 19 &amp; 20 these two are super close. They are both so fun, super sweet and too cute. We can’t wait to see these two on the dance floor!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?f=tweets&q=%23fishmanandwife
  - title: facebook
    url: https://www.facebook.com/search/str/%23fishmanandwife/keywords_top
  - title: instagram
    url: https://www.instagram.com/explore/tags/fishmanandwife/
  - title: github
    url: http://github.com/adamfishman/fishmanandwife

# Postal address (add as many lines as necessary)
address:
  - line: "668 Euclid Ave #312"
  - line: Cleveland, OH 44114

# Build settings
markdown: kramdown
permalink: pretty
